### PR TITLE
Add string.split function

### PR DESCRIPTION
**Pull request by Lejo1**
Adds the default minetest string.split function.
I know it's just one helper function but it were also asked in #470 and should be pretty safe.
A player could anyway add it to his controller:
``` Lua
--  Copied from mt code: https://github.com/minetest/minetest/blob/0df646e0689b5324c7bdb13205c2a63e42ebe8e8/builtin/common/misc_helpers.lua#L169
function string.split(str, delim, include_empty, max_splits, sep_is_pattern)
	delim = delim or ","
	max_splits = max_splits or -2
	local items = {}
	local pos, len = 1, #str
	local plain = not sep_is_pattern
	max_splits = max_splits + 1
	repeat
		local np, npe = string.find(str, delim, pos, plain)
		np, npe = (np or (len+1)), (npe or (len+1))
		if (not np) or (max_splits == 1) then
			np = len + 1
			npe = np
		end
		local s = string.sub(str, pos, np - 1)
		if include_empty or (s ~= "") then
			max_splits = max_splits - 1
			items[#items + 1] = s
		end
		pos = npe + 1
	until (max_splits == 0) or (pos > (len + 1))
	return items
end
```
We could also set the max_splits to a specific value to be 100 % sure.

### CODE REVIEW

**Comment by Lejo1** [comment]
Just one side note:
We have a secure string.find function, but string.split uses the normal one. Is that insecure?

I’m pretty unsure about this cause I don’t know why we need a secure find function

**Comment by SmallJoker** [comment]
Right. `string.split` requires a custom safe implementation according to
https://github.com/minetest-mods/mesecons/blob/f1ff09277011dd43d253184e3c7c660625a509ca/mesecons_luacontroller/init.lua#L223-L228

**Comment by DS-Minetest** [comment]
Just do the same as for `string.find`:
```lua
-- do not allow pattern matching in string.split (see string.find for details)
local function safe_string_split(...)
	if select(5, ...) then
		debug.sethook() -- Clear hook
		error("string.split: 'sep_is_pattern' (fifth parameter) may not be used in a Luacontroller")
	end

	return string.split(...)
end
```
I wonder what other [helper functions](
https://github.com/minetest/minetest/blob/44458896d9097c15c722c5bffb3d72e14962b7ce/doc/lua_api.txt#L2839-L2907) it might be worth adding to the luacontroller.

**Comment by Lejo1** [comment]
> Just do the same as for `string.find`

Thanks, did that!

**Comment by Lejo1** [comment]
Included in #507

**Pull request merged**
