### PR TITLE
make is_ground_content to false

### LINKED ISSUE #295: Mesecons nodes can be destroyed by cave generator
I noticed that many Mesecons nodes do not have `is_ground_content = false` set (default is `true`). This means, all those nodes are possible victims for the cave generator.
Please add `is_ground_content = false` to all nodes.

### PR DESCRIPTION
**Pull request by DS-Minetest**
Fixes #295.

### CODE REVIEW

**Comment by numberZero** [comment]
`is_ground_content` defaults to false.

**Comment by sfan5** [comment]
[it doesn't](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4524)

**Comment by numberZero** [comment]
@sfan5 https://github.com/minetest/minetest/blob/master/src/nodedef.cpp#L356

**Comment by sfan5** [comment]
@numberZero https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L689

**Pull request merged**
