### PR TITLE
Sticky block: Add texture, sounds and groups

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR does the following:

* Add a texture for the sticky block. It's a wooden box with glue
* Rename the node from “All-Faces Sticky Block” to “Sticky Block” because it is (currently) the only one. Can be reverted later, of course
* Add node sounds
* Add proper grouping (choppy, oddly_breakable_by_hand)

Preview of texture:
https://i.imgur.com/E29MeFO.png

### CODE REVIEW

**Comment by C1ffisme** [comment]
The texture is a bit too yellow for my taste... Could you make it a bit more green?

**Comment by VanessaE** [comment]
If it were up to me, it would be a plain-ish block, with glue painted onto just the middle, similar to a sticky piston.

**Comment by Wuzzy2** [comment]
xD @VanessaE.
Actually, did exactly that. I basically just combined the glue texture (blurred) with the piston head (slight color change at the border).
But yeah, I can understand why you hate this texture. I'm not a huge fan either. :-(
@C1ffisme: “More green” doesn't make sense at all to me. The glue item is yellow, not green. Same for the sticky piston head.

**Comment by VanessaE** [comment]
I dunno, to my eyes it looks like you spread the glue across the whole surface instead of just a glob in the center.

**Comment by VanessaE** [comment]
better.

**Comment by numberZero** [comment]
@Wuzzy2 

Also it’s fine that you don’t add crafting recipes as the block is still buggy.

**Comment by Wuzzy2** [comment]
I added the new texture in my repo and squashed the commits.

**Pull request merged**
