### PR TITLE
Defer on_placenode to a step after a node is moved

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
I noticed a problem, shown here:

screenshot_20220215_220644
screenshot_20220215_220718

The logic gate should not be turning off.

I think this bug affects things that use `action_change`. To fix the bug, I deferred `on_placenode` for one step. One strange thing about `on_placenode` is that it takes immediate action when placing conductors. I think this is the reason for the problem, but I didn't want to change `on_placenode` everywhere.

This change could affect some Mesecons devices as it slows down some processes by one step.

### CODE REVIEW

**Review by SmallJoker — COMMENTED** [review]
LGTM. Will merge in a few days unless there's an objection.

**Comment by Desour** [comment]
>This change could affect some Mesecons devices as it slows down some processes by one step.

Tested, it does.

Example (using [meseconometer](https://github.com/Desour/meseconometer)):
screenshot_20221120_140323
master:
```
[0.0,"C","on"],
[38.0,"D","on"],
[39.0,"B","on"],    -- just one server-step later
[66.0,"D","off"],
[68.0,"B","off"],
[104.0,"C","off"]
```
PR:
```
[0.0,"C","on"],
[35.0,"D","on"],
[37.0,"B","on"], -- two server-steps later
[50.0,"D","off"],
[52.0,"B","off"],
[89.0,"C","off"]
```

Some people (including me) rely on exact timings. Could the issue be fixed in some other way?

**Comment by TurkeyMcMac** [comment]
I think there's a better way:

```patch
diff --git a/mesecons/init.lua b/mesecons/init.lua
index 83e611b..c7adcb7 100644
--- a/mesecons/init.lua
+++ b/mesecons/init.lua
@@ -90,7 +90,7 @@ function mesecon.receptor_on(pos, rules)
 	mesecon.queue:add_action(pos, "receptor_on", {rules}, nil, rules)
 end
 
-mesecon.queue:add_function("receptor_off", function (pos, rules)
+mesecon.queue:add_function("receptor_off", function (pos, rules, check)
 	rules = rules or mesecon.rules.default
 
 	-- Call turnoff on all linking positions
@@ -98,23 +98,25 @@ mesecon.queue:add_function("receptor_off", function (pos, rules)
 		local np = vector.add(pos, rule)
 		local rulenames = mesecon.rules_link_rule_all(pos, rule)
 		for _, rulename in ipairs(rulenames) do
-			mesecon.vm_begin()
-			mesecon.changesignal(np, minetest.get_node(np), rulename, mesecon.state.off, 2)
-
-			-- Turnoff returns true if turnoff process was successful, no onstate receptor
-			-- was found along the way. Commit changes that were made in voxelmanip. If turnoff
-			-- returns true, an onstate receptor was found, abort voxelmanip transaction.
-			if (mesecon.turnoff(np, rulename)) then
-				mesecon.vm_commit()
-			else
-				mesecon.vm_abort()
+			if not check or not mesecon.is_powered(np, rulename) then
+				mesecon.vm_begin()
+				mesecon.changesignal(np, minetest.get_node(np), rulename, mesecon.state.off, 2)
+
+				-- Turnoff returns true if turnoff process was successful, no onstate receptor
+				-- was found along the way. Commit changes that were made in voxelmanip. If turnoff
+				-- returns true, an onstate receptor was found, abort voxelmanip transaction.
+				if (mesecon.turnoff(np, rulename)) then
+					mesecon.vm_commit()
+				else
+					mesecon.vm_abort()
+				end
 			end
 		end
 	end
 end)
 
-function mesecon.receptor_off(pos, rules)
-	mesecon.queue:add_action(pos, "receptor_off", {rules}, nil, rules)
+function mesecon.receptor_off(pos, rules, check)
+	mesecon.queue:add_action(pos, "receptor_off", {rules, check}, nil, rules)
 end
 
 
diff --git a/mesecons/services.lua b/mesecons/services.lua
index f33aee4..52b8abc 100644
--- a/mesecons/services.lua
+++ b/mesecons/services.lua
@@ -56,11 +56,11 @@ mesecon.on_placenode = function(pos, node)
 	end
 end
 
-mesecon.on_dignode = function(pos, node)
+mesecon.on_dignode = function(pos, node, check)
 	if mesecon.is_conductor_on(node) then
-		mesecon.receptor_off(pos, mesecon.conductor_get_rules(node))
+		mesecon.receptor_off(pos, mesecon.conductor_get_rules(node), check)
 	elseif mesecon.is_receptor_on(node.name) then
-		mesecon.receptor_off(pos, mesecon.receptor_get_rules(node))
+		mesecon.receptor_off(pos, mesecon.receptor_get_rules(node), check)
 	end
 
 	mesecon.execute_autoconnect_hooks_queue(pos, node)
@@ -74,7 +74,9 @@ function mesecon.on_blastnode(pos)
 end
 
 minetest.register_on_placenode(mesecon.on_placenode)
-minetest.register_on_dignode(mesecon.on_dignode)
+minetest.register_on_dignode(function(pos, node)
+	return mesecon.on_dignode(pos, node)
+end)
 
 -- Overheating service for fast circuits
 local OVERHEAT_MAX = mesecon.setting("overheat_max", 20)
diff --git a/mesecons_mvps/init.lua b/mesecons_mvps/init.lua
index c047ed9..20c3d95 100644
--- a/mesecons_mvps/init.lua
+++ b/mesecons_mvps/init.lua
@@ -224,7 +224,7 @@ function mesecon.mvps_push_or_pull(pos, stackdir, movedir, maximum, all_pull_sti
 
 	-- update mesecons for removed nodes ( has to be done after all nodes have been removed )
 	for _, n in ipairs(nodes) do
-		mesecon.on_dignode(n.pos, n.node)
+		mesecon.on_dignode(n.pos, n.node, true)
 	end
 
 	-- add nodes

```

**Comment by Desour** [comment]
That looks quite hacky to me, and I'm not sure what it does exactly. So, you're checking if the removed node (=air) at that pos is powered (by some node that is not currently mvps-moved) via the rules of the old node?

-------------

I'm more and more getting the feeling that mesecons' logic is completely broken, especially if nodes start moving around.
We need more resilience to map changes within the execution of an actionqueue step. (Even so much that you can do an actionqueue step over multiple server-steps, but that's a different story.)

**Comment by TurkeyMcMac** [comment]
The new code checks that the link it's turning off is still unpowered before proceeding.

Fixing the movement code is like playing Whack-A-Mole. A while ago I tried letting actionqueue items be moved by mvps, but that didn't work for some reason.

**Comment by TurkeyMcMac** [comment]
This has been superseded.

**Pull request closed without merging**
