### PR TITLE
Use mod.conf for dependencies

### PR DESCRIPTION
**Pull request by Panquesito7**
Title says it all.

### CODE REVIEW

**Comment by Panquesito7** [comment]
Ping?

**Comment by Panquesito7** [comment]
@sofar.

**Comment by numberZero** [comment]
1. Why keep `depends.txt`? (Mesecons don’t support old MT versions anyway)
2. “No newline at end of file.” Fix please, it can cause problems with further diffs (most programs treat LF [newline] as line *terminator* while your editor seem to treat is as a *separator*).

**Comment by Panquesito7** [comment]
@numberZero, both issues have been fixed now.

**Pull request merged**
