### PR TITLE
add conversation recipes for lua- and microcontroller

### LINKED ISSUE #339: Luacontroller and Microcontroller have the same recipe
This makes one or the other impossible to craft.

### PR DESCRIPTION
**Pull request by DS-Minetest**
I made my own PR for this now.
Fixes #339, closes #353 and closes #351.
Look to "Files changed".

### CODE REVIEW

**Comment by Brackston** [comment]
This appears to make the devices interchangeable. It that correct?

**Comment by DS-Minetest** [comment]
Well, they have the same value based on their recipe, so why not make it interchangeable?
The microcontroller is only directly craftable if the luacontroller is deactivated. This solves the overlapping problem.

**Comment by Brackston** [comment]
> The microcontroller is only directly craftable if the luacontroller is deactivated. This solves the overlapping problem.
What happens if both of the controllers are desired?

**Comment by DS-Minetest** [comment]
>What happens if both of the controllers are desired?

Then it isn't directly craftable but indirectly via a luacontroller and the conversation recipe.

**Comment by Brackston** [comment]
Thank you, DS-Minetest.

**Pull request merged**
