### PR TITLE
Add 6 new lightstone colors

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds 6 new lightstones: White, orange, pink, magenta, violet and cyan. Craftable with 3 dyes of the same color, 1 torch and 1 mesecon.

Screenshots:

New lightstones left, current lightstones right.

Colors intentionally left out: Dark green, black and brown. I have tried these colors but I figured they look very ugly; the green and (new) orange lightstone are just fine and don't need darker versions IMO.
Black doesn't feel right for something which glows and also doesn't look good.

### CODE REVIEW

**Comment by Jeija** [comment]
I'm not sure about orange, pink and violet. Cyan, magenta and white are good for consistency and will be accepted [as I already mentioned](https://github.com/Jeija/minetest-mod-mesecons/issues/323#issuecomment-280574635). Everyone: Please comment with your thoughts on adding orange, pink and violet!

Also, please make sure to add documentation (3d views of the blocks, craft recipes, text) for mesecons.net as soon as it is decided which colors should be included.

**Comment by Wuzzy2** [comment]
Why not orange? It's a secondary color. So is violet. If cyan (color between green and blue) is valid, then so is orange (between red and yellow) and violet (between red and blue).

I'm not happy about adding 6 near-identical pages, and I also don't know how to make lightstone images which don't look like shit.

**Comment by VanessaE** [comment]
I don't like the idea only because it adds new textures and more nodes, when there's an engine feature that should be used instead.  At the very least, @Wuzzy2, you should be using the { name = "foo.png", color=bar } method to colorize the node, and just two base textures for all of them.

**Comment by Jeija** [comment]
@Wuzzy2: No, since we're talking about additive color mixing here, we have [red, green and blue as primary colors and cyan, yellow and magenta in between](https://upload.wikimedia.org/wikipedia/commons/c/c2/AdditiveColor.svg). This is also the reason why I agreed to adding cyan, magenta and white in the first place, since yellow as a secondary color was already included without the other counterparts for balance.

@VanessaE: That sounds like a good idea 👍 . But we need to make sure to maintain backwards compatibility since `mesecon.lightstone_add` could potentially be used by other mods. So maybe we need a new lightstone-registration function for your proposal.

**Comment by VanessaE** [comment]
It wouldn't require a new function.  You could simply hard-code the generic textures' filenames into the two register_node() calls and have the lightstone_add() function just discard the filenames given to it (that way the API doesn't change).

There might be a mod or two that looks for or uses the current lightstone textures for some reason, but those could easily be adapted (and such usage should be discouraged anyway).

**Comment by VanessaE** [comment]
Hm, I forgot to account for passing along the actual color of the node...  So that's an extra field after the description.

If you wanted to avoid the need for the extra `nil` fields in the original calls, check the contents of the 'desc' field at the start of lightstone_add().  If that field is nil, assume the calling mod is passing a color name, dye, description, and color value, but no filenames.  E.g. four fields instead of five.

**Comment by sofar** [comment]
Needs resolution (open for over a month, no comments).

I suggest merging as-is and resolving the paint/node coloring changes at a later point.

**Comment by numberZero** [comment]
I like the idea, and while I don’t like the exact colors (orange is too brownish, pink is very strange, fuchsia could fit better than magenta), I don’t mind merging as-is.

*OT: my spellchecker accidentally switched from default `English (United States)` to `English (Hong Kong)`. How?!..*

**Comment by Wuzzy2** [comment]
Still not resolved. :-(

**Comment by numberZero** [comment]
Mergable, either as-is or with https://github.com/Wuzzy2/minetest-mod-mesecons/pull/1
screenshot_20170913_220814
screenshot_20170913_220802
@Wuzzy2

**Pull request merged**
