### PR TITLE
Ignore Eclipse project files & directories

### PR DESCRIPTION
**Pull request by AntumDeluge**
Simplification for developers using the [Eclipse IDE](https://eclipse.org/ide/).

### CODE REVIEW

**Comment by sfan5** [comment]
People actually use eclipse to develop lua?

**Comment by numberZero** [comment]
@sfan5 Well, there is some support for that. I tried to use it some time ago, and it seemed to work rather well, but as always with Eclipse, I just couldn’t configure it well enough, and Eclipse doesn’t forgive misconfiguration.
By the way, what’s the IDE you use for Lua?

**Comment by numberZero** [comment]
On topic: I’m mostly neutral. Of course we can’t support each and every IDE, but the changes requested are minor, while Eclipse is a rather common product. On the other hand, `.git/info/exclude` may be used for that as well.

**Comment by AntumDeluge** [comment]
Eclipse does not have good Lua support. Supposedly, the [LiClipse](https://marketplace.eclipse.org/content/liclipse) plugin has an editor that supports Lua, but it doesn't even appear to have syntax highlighting.

I did just install the [Lua Development Tools](https://marketplace.eclipse.org/content/lua-development-tools) plugin, & it *does* include a text editor with syntax highlighting. But other than that, I have not tested it & don't know what else it can do.

I just use Eclipse because it's what I use for my other projects that involve C++, Java, & Python. And it makes managing my Git repos easier (IMO).

**Comment by AntumDeluge** [comment]
Decided to create a *.gitignore* in my home directory & added the global `core.excludesFile` in my *~/.gitconfig* so that globally I don't have to worry about ignoring files for individual projects.

```
$ git config --global --add core.excludesFile "~/gitignore"
$ cat ~/gitconfig
...
[core]
	editor = nano
	excludesFile = ~/.gitignore
...
```

**Pull request closed without merging**
