### PR TITLE
Luacontroller nodetimer

### PR DESCRIPTION
**Pull request by thomasrudin**
Adds optional nodetimer based luacontroller interrupts, useful for server owners, disabled by default:

Original idea by Joe7575 (https://forum.minetest.net/memberlist.php?mode=viewprofile&u=21063)

Settings:
```
# enable nodetimer based luacontroller interrupts (only active if a player is near them)
mesecon.luacontroller_nodetimer = true
```

### CODE REVIEW

**Comment by numberZero** [comment]
Normally, several interrupts (with different names or unnamed) may be queued simultaneously, your code doesn’t support that.

**Comment by thomasrudin** [comment]
Thats right, only one interrupt is possible now with this patch and further interrupt() calls overrule the previous ones.
But in my opinion the default mesecons mod is (sadly) not ready for heavy multiplayer servers without resorting to purging the action-queue every few weeks :(

I'm open for suggestions...

**Comment by thomasrudin** [comment]
setting renamed and iid support in node_timer interrupt dropped
btw: is there a place to document settings?

**Comment by DS-Minetest** [comment]
>is there a place to document settings?

Yes, `settingtypes.txt`.
https://github.com/minetest-mods/mesecons/blob/master/settingtypes.txt

**Comment by numberZero** [comment]
@DS-Minetest Is this OK?

**Comment by DS-Minetest** [comment]
Yes, I think.

**Comment by thomasrudin** [comment]
Thx for merging

>  However I wonder whether how often this feature will be used.

Its been used already by a couple of servers (found some forum-topics discussion the patch) but now there is an official way with the "stock" mesecons mod :+1:

**Comment by gpcf** [comment]
I think it was wrong to disable iids in this PR. After all, they can be used to differentiate interrupt types.

**Comment by gpcf** [comment]
I can provide several code examples from Linuxworks server that work with one interrupt but setting iids for different actions.

**Comment by thomasrudin** [comment]
> I think it was wrong to disable iids in this PR. After all, they can be used to differentiate interrupt types.

That was a suggestion from @numberZero, the reasoning was that the last set interrupt id will always override the previously set ones, no matter what.

This may be a good case for a setting to preserve backwards compatibility..

> I can provide several code examples from Linuxworks server that work with one interrupt but setting iids for different actions.

Yes, please :smile: do you have a public repo somewhere (i searched on https://git.bananach.space/ but haven't found anything...)

**Comment by gpcf** [comment]
Those code examples are only in-world. I will post them here with consent of the players who wrote them.

**Comment by gpcf** [comment]
Here is the program of an automatic Tree planter
```

-- mesecon

-- A   Setzlinge / anpflanzen
-- B   Kettensäge verwenden
-- C   Ein/Aus  (Schalter)
-- D   düngen / Knochenmehl verwenden


-- digiline

-- lcd                LCD-Anzeige
-- chainsaw    Sensorrohr vor Node-Breaker (Kettensäge)
-- bonemeal   Injector für Knochenmehlnachschub
-- nachladen  Injector zum Entnehmen der Kettensäge
-- detector      node detector 


-- Funktion(en)

local function anzeigen()
      digiline_send("lcd",mem.status)
end



if event.iid == "anzeigen" then
     digiline_send("lcd",mem.status)
     return
end

if event.iid == "laden" then
     if mem.status == "aus" then return end
     mem.status = "laden"
     mem.stop = ""
     digiline_send("nachladen", {  } )
--     digiline_send("bonemeal", { count=19 } )
--     interrupt(0,"anzeigen")
     anzeigen()
     return
end

if event.iid == "status" then
     if mem.status == "aus" then return end
     mem.status = "status"
     digiline_send("detector","GET")
--     interrupt(0,"anzeigen")
     anzeigen()
     return
end

if event.iid == "anpflanzen"  then
     if mem.status == "aus" then return end
     port.a = true
     interrupt(1,"anpflanzen2")
     return
end

if event.iid == "anpflanzen2" then
     port.a = false
     interrupt(1,"status")
     mem.zuletzt = "anpflanzen"
     return
end

if event.iid == "duengen" then
     if mem.status == "aus" then return end
     port.d = true
     interrupt(1,"duengen2")
     return
end

if event.iid == "duengen2" then
     port.d = false
     interrupt(1,"status")
     mem.zuletzt = "duengen"
     return
end

if event.iid == "faellen" then
     if mem.status == "aus" then return end
     digiline_send("bonemeal", { count=10 } )    
     port.b = true
     mem.zyklen = mem.zyklen+1
     if mem.redwood then mem.zyklen = mem.zyklen+3 end
     if mem.willow then mem.zyklen = mem.zyklen+1 end
     mem.status = string.format("faellen |  %d / %d",mem.zyklen,mem.maxzyklen)
--     interrupt(0,"anzeigen")
     anzeigen()
     interrupt(1,"faellen2")
     return
end

if event.iid == "faellen2" then
     port.b = false
     mem.zuletzt = "faellen"
     if mem.zyklen >= mem.maxzyklen then
          interrupt(1,"laden")
          return
     end
     interrupt(1,"status")
     return
end

if event.iid == "stop" then
     if mem.status == "aus" then return end
--    interrupt(60,"stop")
     digiline_send("lcd","stop | " .. mem.stop)
 
     interrupt(60,"neustart")
   return
end

if event.iid == "neustart" then
     if mem.status == "aus" then return end
     mem.stop = ""
     mem.status = "start"
     mem.zuletzt = ""
     interrupt(0,"laden")
    return
end


if event.type == "digiline" then 
     if mem.status == "aus" then return end
     if event.channel == "chainsaw" then
          mem.status = "geladen"
          mem.zyklen = 0
--          interrupt(0,"anzeigen")
          anzeigen()
          interrupt(1,"status")
          return
     end
     if event.channel == "detector" then
          if event.msg == "air" then
               if mem.zuletzt == "anpflanzen" then
                    mem.stop = "keine Setzlinge mehr vorhanden"
                    interrupt(0,"stop")
                    return
               end   
               if mem.zuletzt == "duengen" then
                    mem.stop = "kein Duenger mehr vorhanden"
                    interrupt(0,"stop")
                    return
               end
               mem.status = "anpflanzen"
               --  interrupt(0,"anzeigen")
               anzeigen()
               interrupt(1,"anpflanzen")
               return
          end
          h = event.msg
          mem.redwood = h:find("redwood",1,true)
          mem.willow = h:find("willow",1,true)
        
          i = h:find("sapling",1,true)
          if not i then
               i = h:find("sprout",1,true)
          end
          if i then
               mem.status = "duengen"
          --     interrupt(0,"anzeigen")
               anzeigen()
               interrupt(1,"duengen")
               return
          end   
 
          i = h:find("trunk",1,true)
          if not i then
               i = h:find("tree",1,true)
          end
          if not i then
               i = h:find("bamboo",1,true)
          end
          if not i then
               i = h:find("_stem",1,true)
          end
          if i  then
               mem.status = "faellen"
 --              interrupt(0,"anzeigen")
               anzeigen()
               interrupt(1,"faellen")
               return
          end        


     end
end    

if event.type == "off" and event.pin.name == "C" then
   interrupt(0,"aus")
   return
end

if event.type == "on" and event.pin.name == "C" then
     mem.status = ""
     mem.zuletzt = ""
     digiline_send("bonemeal", {  } )    
     interrupt(0,"laden")
     return
end
    
if event.iid == "aus" then
   mem.status = "aus"
--   interrupt(0,"anzeigen")
     anzeigen()
  -- interrupt(20,"aus")
   return
end

if event.type == "program" then
     mem.status = "start"
     mem.zuletzt = ""
     if  pin.c then
--          interrupt(0,"anzeigen")
          anzeigen()
          interrupt(1,"laden")
     else
          interrupt(0,"aus")
     end
     mem.zyklen = 0
     mem.maxzyklen = 35
--     mem.maxzyklen = 20
--     mem.maxzyklen = 10
       return
end

-- Ende der Datei
```

**Comment by thomasrudin** [comment]
@numberZero @DS-Minetest i'd like to draft a new PR to re-enable the iid's even if the lightweight interrupts are enabled, any objections?

**Comment by DS-Minetest** [comment]
@gpcf Would you mind putting that code into a `<details>...</details>`? :slightly_smiling_face: 

It is indeed true that there are probably many players who do not use parallel interrupts but still different iids.
However, iids have to be preserved over server restarts. (Actionqueue does this with params.)
I suggest that you save the iid in a table that has node pos hashes as keys and the iids at that positions as values and save this table on shutdown (see also [this old, hence not optimal, code](https://github.com/minetest-mods/mesecons/blob/7013f2e5d47ff2d21fb66fe82966a34ece947eec/mesecons/actionqueue.lua#L98-L105)).
But if you do this anyway, you could also allow multiple iids, just save the current and a queue of the next ones with their time.

**Pull request merged**
