### PR TITLE
Add bower compatibility

### PR DESCRIPTION
**Pull request by diogo-gomes**

### CODE REVIEW

**Comment by numberZero** [comment]
> Mesecons is a mod...

modpack, not mod. Also, is there any support for that in bower?

**Comment by diogo-gomes** [comment]
I simple paste the description of README.md. **The README.md it's wrong?**

Yes, with bower.json, **Bower auto detects mesecons version**.

When user type `bower update` it auto update to fresh stable version.

You can read more about Bower [here](https://bower.io/) and about Minetest Bower [here](https://minetest-bower.herokuapp.com/).

**Comment by numberZero** [comment]
> I just paste the description of README.md. The README.md is wrong?

Sorry, didn’t notice that. Mesecons are still called a mod, despite being a modpack for several years.

So, if you are sure this will work, I have nothing against. Bower may be a good thing to support.
Just one notice: bower documentation tells the description is limited to 140 characters, while yours has 250, it may be truncated.

**Comment by diogo-gomes** [comment]
@numberZero

Please review the description.

Thanks

**Comment by numberZero** [comment]
Acceptable.
@sfan5 do you approve this?

**Pull request merged**
