### PR TITLE
Fix crash when error()ing an invalid value

### PR DESCRIPTION
**Pull request by cheapie**

### CODE REVIEW

**Comment by sofar** [comment]
:+1:

**Comment by DS-Minetest** [comment]
Could you please use `tostring` instead of `dump`? It now adds extra `"`s and if it's a table, it would give new lines that don't fit into the formspec.

**Comment by numberZero** [comment]
@DS-Minetest Er, the error message is unreadable anyway, so its formatting, basically, doesn’t matter. The crash must be prevented.

**Comment by DS-Minetest** [comment]
Actually the error messages are readable and useful IMO and using `tostring` would also fix the bug.

**Comment by numberZero** [comment]
564bdc2
As `error()` expects a message (that is, a string), handling of non-string values may be arbitrary as long as it works somehow.

**Pull request closed without merging**
